### ISSUE TITLE
Ubuntu 16.04 (16.10) compiling with -flto

### ISSUE THREAD

**Issue by boput** [dds-bridge/dds#63]
Compiling dds ends with sequence of "ar" complains like
ar: dds.o: plugin needed to handle lto object
etc... for other objects

Question: Which plugin is needed for lto object for ar not to complain?

**Comment by Afwas** [comment]
This is an issue with gcc, not with dds. If you google you'll find useful comments [1][2] that should help solve your issues.

Have a nice day.

Examples:
[1] https://bugs.archlinux.org/task/43367
[2] https://www.spinics.net/lists/gcchelp/msg44831.html
comment: "Use gcc-nm instead of nm. Same applies for ar and ranlib, btw."

**Comment by boput** [comment]
Thank you!

Best,

On Nov 30, 2016 21:07, Foppe Hemminga <notifications@github.com> wrote:

This is an issue with gcc, not with dds. If you google you'll find useful comments [1][2] that should help solve your issues.

Have a nice day.

Examples:
[1] https://bugs.archlinux.org/task/43367
[2] https://www.spinics.net/lists/gcchelp/msg44831.html
comment: "Use gcc-nm instead of nm. Same applies for ar and ranlib, btw."
